name: migration
on: 
  pull_request:
    paths:
      - 'migrations/**'

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang
    env:
      DATABASE_HOST: postgres
      DATABASE_NAME: postgres
      DATABASE_USER: test_user
      DATABASE_PASSWORD: test_pass
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Migration
        id: go-migration
        run: |
          result="$(./third_party/bin/sql-migrate up -dryrun -env actions | sed -z 's/\n/%0A/g')"
          echo ::set-output name=test::$result

      - name: Comment
        uses: actions/github-script@v4
        with:
          script: |
            const result = `${{steps.go-migration.outputs.test}}`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: result,
            })

